import localFont from "next/font/local";
import Navbar from "@/components/navbar/page";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar - stays fixed or sticky */}
        <Navbar />

        {/* Main content area */}
        <div className="bg-red-400 h-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
